version: '3.8'

services:
  db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - 5432:5432

  api:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8000:8000
